# Topic Modeling

## Introduction

Another popular text analysis technique is called topic modeling. The ultimate goal of topic modeling is to find various topics that are present in your corpus. Each document in the corpus will be made up of at least one topic, if not multiple topics.

In this notebook, we will be covering the steps on how to do **Latent Dirichlet Allocation (LDA)**, which is one of many topic modeling techniques. It was specifically designed for text data.

To use a topic modeling technique, you need to provide (1) a document-term matrix and (2) the number of topics you would like the algorithm to pick up.

Once the topic modeling technique is applied, your job as a human is to interpret the results and see if the mix of words in each topic make sense. If they don't make sense, you can try changing up the number of topics, the terms in the document-term matrix, model parameters, or even try a different model.

## Topic Modeling - Attempt #1 (All Text)

In [1]:
# Let's read in our document-term matrix
import pandas as pd
import pickle

data = pd.read_pickle('dtm_stop.pkl')
data.sample(5)

,aaron,aarons,abagtha,abandon,abandoned,abarim,abase,abased,abashed,abated,...,zophim,zorah,zorathites,zorites,zuar,zuph,zur,zuriel,zurishaddai,zuzim
Jeremiah,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Numbers,100,1,0,0,0,3,0,0,0,1,...,1,0,0,0,5,0,2,1,5,0
Malachi,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Habakkuk,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Exodus,107,9,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [2]:
# !pip install gensim

In [3]:
# Import the necessary modules for LDA with gensim
# Terminal / Anaconda Navigator: conda install -c conda-forge gensim
from gensim import matutils, models
import scipy.sparse

# import logging
# logging.basicConfig(format='%(asctime)s : %(levelname)s : %(message)s', level=logging.INFO)

In [4]:
# One of the required inputs is a term-document matrix
tdm = data.transpose()
tdm.head()

,Amos,Chronicles,Daniel,Deuteronomy,Ecclesiastes,Esther,Exodus,Ezekiel,EzraNehemiah,Genesis,...,Nahum,Numbers,Obadiah,Proverbs,Psalms,Ruth,Samuel,SongofSongs,Zechariah,Zephaniah
aaron,0,24,0,4,0,0,107,0,3,0,...,0,100,0,0,8,0,2,0,0,0
aarons,0,0,0,0,0,0,9,0,0,0,...,0,1,0,0,1,0,0,0,0,0
abagtha,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
abandon,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
abandoned,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [5]:
# We're going to put the term-document matrix into a new gensim format, from df --> sparse matrix --> gensim corpus
sparse_counts = scipy.sparse.csr_matrix(tdm)
corpus = matutils.Sparse2Corpus(sparse_counts)

In [6]:
# Gensim also requires dictionary of the all terms and their respective location in the term-document matrix
cv = pickle.load(open("cv_stop.pkl", "rb"))
id2word = dict((v, k) for k, v in cv.vocabulary_.items())

Now that we have the corpus (term-document matrix) and id2word (dictionary of location: term), we need to specify two other parameters - the number of topics and the number of passes. Let's start the number of topics at 2, see if the results make sense, and increase the number from there.

In [7]:
# Now that we have the corpus (term-document matrix) and id2word (dictionary of location: term),
# we need to specify two other parameters as well - the number of topics and the number of passes
lda = models.LdaModel(corpus=corpus, id2word=id2word, num_topics=2, passes=10)
lda.print_topics()

[(0,
  '0.009*"shalt" + 0.007*"king" + 0.007*"saith" + 0.005*"hast" + 0.005*"earth" + 0.005*"forth" + 0.005*"heart" + 0.004*"away" + 0.004*"like" + 0.004*"say"'),
 (1,
  '0.017*"king" + 0.011*"david" + 0.009*"sons" + 0.008*"went" + 0.006*"saying" + 0.006*"judah" + 0.005*"moses" + 0.005*"did" + 0.005*"priest" + 0.005*"saul"')]

In [8]:
# LDA for num_topics = 3
lda = models.LdaModel(corpus=corpus, id2word=id2word, num_topics=3, passes=10)
lda.print_topics()

[(0,
  '0.023*"king" + 0.012*"david" + 0.009*"went" + 0.008*"sons" + 0.007*"judah" + 0.006*"did" + 0.006*"saying" + 0.005*"jerusalem" + 0.005*"city" + 0.005*"kings"'),
 (1,
  '0.009*"saith" + 0.006*"heart" + 0.006*"hast" + 0.006*"earth" + 0.006*"like" + 0.006*"king" + 0.005*"away" + 0.005*"forth" + 0.004*"evil" + 0.004*"shalt"'),
 (2,
  '0.016*"shalt" + 0.011*"moses" + 0.007*"sons" + 0.006*"saying" + 0.006*"egypt" + 0.005*"went" + 0.005*"aaron" + 0.005*"priest" + 0.005*"bring" + 0.005*"according"')]

In [9]:
# LDA for num_topics = 4
lda = models.LdaModel(corpus=corpus, id2word=id2word, num_topics=4, passes=10)
lda.print_topics()

[(0,
  '0.009*"saith" + 0.007*"heart" + 0.006*"hast" + 0.006*"earth" + 0.006*"like" + 0.005*"evil" + 0.005*"away" + 0.005*"king" + 0.005*"soul" + 0.004*"say"'),
 (1,
  '0.011*"david" + 0.011*"sons" + 0.010*"shalt" + 0.009*"moses" + 0.007*"king" + 0.007*"went" + 0.006*"saying" + 0.005*"saul" + 0.005*"father" + 0.004*"took"'),
 (2,
  '0.011*"saith" + 0.007*"shalt" + 0.007*"forth" + 0.006*"king" + 0.005*"hast" + 0.005*"nations" + 0.005*"know" + 0.005*"say" + 0.005*"earth" + 0.004*"midst"'),
 (3,
  '0.024*"king" + 0.009*"went" + 0.009*"shalt" + 0.007*"did" + 0.007*"judah" + 0.007*"kings" + 0.006*"city" + 0.006*"saying" + 0.006*"jerusalem" + 0.005*"fathers"')]

These topics aren't looking too great. We've tried modifying our parameters. Let's try modifying our terms list as well.

## Topic Modeling - Attempt #2 (Nouns Only)

One popular trick is to look only at terms that are from one part of speech (only nouns, only adjectives, etc.). Check out the UPenn tag set: https://www.ling.upenn.edu/courses/Fall_2003/ling001/penn_treebank_pos.html.

In [10]:
# Let's create a function to pull out nouns from a string of text
from nltk import word_tokenize, pos_tag

def nouns(text):
    '''Given a string of text, tokenize the text and pull out only the nouns.'''
    is_noun = lambda pos: pos[:2] == 'NN'
    tokenized = word_tokenize(text)
    all_nouns = [word for (word, pos) in pos_tag(tokenized) if is_noun(pos)] 
    return ' '.join(all_nouns)

In [11]:
# Read in the cleaned data, before the CountVectorizer step
data_clean = pd.read_pickle('data_clean.pkl')
data_clean

                                                     transcript  total_words
Amos           the words of amos who was among the herdmen o...        38376
Chronicles    Â  adam seth enoshÂ  kenan mahalalel jaredÂ  enoc...        32707
Daniel         in the third year of the reign of jehoiakim k...        24312
Deuteronomy    these are the words which moses spoke unto al...        32656
Ecclesiastes   the words of koheleth the son of david king i...        28595
Esther         now it came to pass in the days of ahasuerust...        19046
Exodus         now these are the names of the sons of israel...        18975
Ezekiel        now it came to pass in the thirtieth year in ...        46058
EzraNehemiah  eÂ  now in the first year of cyrus king of pers...        48206
Genesis        in the beginning god created the heaven and t...        36932
Habakkuk       the burden which habakkuk the prophet did see...        42851
Haggai         in the second year of darius the king in the ...        39517
Hosea          the word of the lord that came unto hosea the...         5193
Isaiah         the vision of isaiah the son of amoz which he...         2011
Jeremiah       the words of jeremiah the son of hilkiah of t...         4166
Job            there was a man in the land of uz whose name ...          656
Joel           the word of the lord that came to joel the so...         1330
Jonah          now the word of the lord came unto jonah the ...         3170
Joshua         now it came to pass after the death of moses ...         1250
Judges         and it came to pass after the death of joshua...         1459
Kings         Â  now king david was old and stricken in years...         1638
Lamentations   how doth the city sit solitary that was full ...         1131
Leviticus      and the lord called unto moses and spoke unto...         6452
Malachi        the burden of the word of the lord to israel ...         1780
Micah          the word of the lord that came to micah the m...        46804
Nahum          the burden of nineveh the book of the vision ...        43655
Numbers        and the lord spoke unto moses in the wilderne...        18254
Obadiah        the vision of obadiah thus saith the lord god...        15150
Proverbs       the proverbs of solomon the son of david king...         2558
Psalms         happy is the man that hath not walked in the ...         2654
Ruth           and it came to pass in the days when the judg...         5622
Samuel        Â  now there was a certain man of ramathaimzoph...         3515
SongofSongs    the song of songs which is solomons let him k...         5713
Zechariah      in the eighth month in the second year of dar...        11755
Zephaniah      the word of the lord which came unto zephania...        18127

In [15]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Yishai\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.

True

In [17]:
nltk.download('averaged_perceptron_tagger')

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\Yishai\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping taggers\averaged_perceptron_tagger.zip.

True

In [43]:
# Apply the nouns function to the transcripts to filter only on nouns
data_nouns = pd.DataFrame(data_clean.transcript.apply(nouns))
data_nouns.head()

                                                     transcript
Amos          words amos herdmen tekoa israel days king juda...
Chronicles    adam kenan methuselah lamech ham japheth sons ...
Daniel        year reign jehoiakim king judah king babylon u...
Deuteronomy   words jordan wilderness arabah suph paran toph...
Ecclesiastes  words son david king vanity vanities vanity va...

In [45]:
# Create a new document-term matrix using only nouns
from sklearn.feature_extraction import text
from sklearn.feature_extraction.text import CountVectorizer

# Re-add the additional stop words since we are recreating the document-term matrix
add_stop_words = ['i', 'hast', 'thou', 'son', 'word', 'thee', 'hath']
stop_words = text.ENGLISH_STOP_WORDS.union(add_stop_words)

# Recreate a document-term matrix with only nouns
cvn = CountVectorizer(stop_words=stop_words)
data_cvn = cvn.fit_transform(data_nouns.transcript)
data_dtmn = pd.DataFrame(data_cvn.toarray(), columns=cvn.get_feature_names())
data_dtmn.index = data_nouns.index
data_dtmn.head()

,aaron,aarons,abagtha,abarim,abase,abda,abdeel,abdi,abdiel,abdon,...,zophai,zophim,zorah,zorathites,zorites,zuar,zuph,zur,zurishaddai,zuzim
Amos,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Chronicles,23,0,0,0,0,0,0,2,1,3,...,1,0,1,2,1,0,1,2,0,0
Daniel,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Deuteronomy,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Ecclesiastes,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [46]:
# Create the gensim corpus
corpusn = matutils.Sparse2Corpus(scipy.sparse.csr_matrix(data_dtmn.transpose()))

# Create the vocabulary dictionary
id2wordn = dict((v, k) for k, v in cvn.vocabulary_.items())

In [47]:
# Let's start with 2 topics
ldan = models.LdaModel(corpus=corpusn, num_topics=2, id2word=id2wordn, passes=10)
ldan.print_topics()

[(0,
  '0.052*"lord" + 0.020*"god" + 0.014*"man" + 0.014*"king" + 0.012*"land" + 0.012*"house" + 0.011*"people" + 0.010*"israel" + 0.010*"hand" + 0.010*"day"'),
 (1,
  '0.041*"lord" + 0.022*"children" + 0.020*"israel" + 0.014*"god" + 0.013*"land" + 0.013*"people" + 0.013*"sons" + 0.012*"moses" + 0.011*"king" + 0.011*"house"')]

In [48]:
# Let's try topics = 3
ldan = models.LdaModel(corpus=corpusn, num_topics=3, id2word=id2wordn, passes=10)
ldan.print_topics()

[(0,
  '0.050*"lord" + 0.019*"god" + 0.019*"land" + 0.015*"children" + 0.014*"shalt" + 0.013*"israel" + 0.012*"people" + 0.012*"man" + 0.011*"day" + 0.011*"moses"'),
 (1,
  '0.046*"lord" + 0.028*"king" + 0.022*"israel" + 0.020*"house" + 0.015*"god" + 0.015*"people" + 0.013*"men" + 0.012*"children" + 0.012*"david" + 0.011*"sons"'),
 (2,
  '0.046*"lord" + 0.019*"god" + 0.014*"man" + 0.010*"heart" + 0.010*"earth" + 0.009*"hand" + 0.008*"men" + 0.008*"day" + 0.008*"people" + 0.008*"king"')]

In [49]:
# Let's try 4 topics
ldan = models.LdaModel(corpus=corpusn, num_topics=4, id2word=id2wordn, passes=10)
ldan.print_topics()

[(0,
  '0.029*"lord" + 0.027*"children" + 0.017*"land" + 0.016*"god" + 0.014*"israel" + 0.011*"sons" + 0.010*"men" + 0.009*"king" + 0.009*"day" + 0.009*"man"'),
 (1,
  '0.048*"lord" + 0.027*"king" + 0.023*"house" + 0.023*"israel" + 0.019*"god" + 0.015*"sons" + 0.013*"people" + 0.011*"judah" + 0.011*"david" + 0.010*"land"'),
 (2,
  '0.052*"lord" + 0.018*"shalt" + 0.018*"god" + 0.016*"israel" + 0.016*"land" + 0.015*"man" + 0.013*"moses" + 0.012*"people" + 0.011*"children" + 0.011*"day"'),
 (3,
  '0.055*"lord" + 0.019*"god" + 0.014*"man" + 0.012*"king" + 0.012*"people" + 0.011*"day" + 0.010*"men" + 0.010*"hand" + 0.009*"land" + 0.009*"earth"')]

## Topic Modeling - Attempt #3 (Nouns and Adjectives)

In [83]:
# Let's create a function to pull out nouns from a string of text
def nouns_adj(text):
    '''Given a string of text, tokenize the text and pull out only the nouns and adjectives.'''
    is_noun_adj = lambda pos: pos[:2] == 'NN' or pos[:2] == 'JJ'
    tokenized = word_tokenize(text)
    nouns_adj = [word for (word, pos) in pos_tag(tokenized) if is_noun_adj(pos)] 
    return ' '.join(nouns_adj)

In [85]:
# Apply the nouns function to the transcripts to filter only nouns and adj
data_nouns_adj = pd.DataFrame(data_clean.transcript.apply(nouns_adj))
data_nouns_adj.sample(9)

                                                     transcript
Kings         david old years clothes heat servants lord you...
Joshua        death moses servant lord lord unto joshua son ...
Obadiah       vision obadiah lord god edom message lord amba...
Habakkuk      burden prophet long o lord cry thou wilt hear ...
Proverbs      proverbs solomon son david king israel wisdom ...
Ruth          days judges famine land certain man bethlehem ...
Lamentations  city sit full people widow great nations princ...
Isaiah        vision isaiah son amoz judah jerusalem days uz...
Leviticus     lord unto moses tent speak children israel man...

In [86]:
# Create a new document-term matrix using only nouns and adjectives, also remove common words with max_df
cvna = CountVectorizer(stop_words=stop_words, max_df=.8)
data_cvna = cvna.fit_transform(data_nouns_adj.transcript)
data_dtmna = pd.DataFrame(data_cvna.toarray(), columns=cvna.get_feature_names())
data_dtmna.index = data_nouns_adj.index
data_dtmna.head()

,aaron,aarons,abagtha,abarim,abase,abatement,abda,abdeel,abdi,abdiel,...,zophai,zophim,zorah,zorathites,zorites,zuar,zuph,zur,zurishaddai,zuzim
Amos,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Chronicles,23,0,0,0,0,0,0,0,2,1,...,1,0,1,2,1,0,1,2,0,0
Daniel,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Deuteronomy,3,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Ecclesiastes,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [87]:
# Create the gensim corpus
corpusna = matutils.Sparse2Corpus(scipy.sparse.csr_matrix(data_dtmna.transpose()))

# Create the vocabulary dictionary
id2wordna = dict((v, k) for k, v in cvna.vocabulary_.items())

In [88]:
# Let's start with 2 topics
ldana = models.LdaModel(corpus=corpusna, num_topics=2, id2word=id2wordna, passes=10)
ldana.print_topics()

[(0,
  '0.013*"david" + 0.009*"father" + 0.006*"years" + 0.006*"fathers" + 0.006*"kings" + 0.006*"priest" + 0.005*"saul" + 0.005*"jerusalem" + 0.005*"servants" + 0.005*"servant"'),
 (1,
  '0.009*"moses" + 0.005*"egypt" + 0.005*"way" + 0.005*"words" + 0.005*"soul" + 0.004*"jerusalem" + 0.004*"fathers" + 0.004*"hosts" + 0.004*"kings" + 0.004*"cities"')]

In [89]:
# Let's try 3 topics
ldana = models.LdaModel(corpus=corpusna, num_topics=3, id2word=id2wordna, passes=10)
ldana.print_topics()

[(0,
  '0.014*"david" + 0.007*"saul" + 0.006*"soul" + 0.006*"moses" + 0.005*"words" + 0.005*"way" + 0.005*"wicked" + 0.004*"righteous" + 0.004*"servant" + 0.004*"servants"'),
 (1,
  '0.007*"egypt" + 0.006*"hosts" + 0.006*"midst" + 0.006*"jerusalem" + 0.006*"jacob" + 0.006*"sword" + 0.005*"father" + 0.005*"way" + 0.005*"cities" + 0.005*"kings"'),
 (2,
  '0.010*"moses" + 0.009*"fathers" + 0.008*"priest" + 0.007*"david" + 0.007*"jerusalem" + 0.006*"father" + 0.006*"kings" + 0.006*"altar" + 0.006*"years" + 0.005*"year"')]

In [90]:
# Let's try 4 topics
ldana = models.LdaModel(corpus=corpusna, num_topics=4, id2word=id2wordna, passes=10)
ldana.print_topics()

[(0,
  '0.017*"moses" + 0.008*"egypt" + 0.008*"priest" + 0.007*"father" + 0.007*"years" + 0.006*"fathers" + 0.006*"aaron" + 0.006*"tent" + 0.006*"altar" + 0.006*"wife"'),
 (1,
  '0.007*"way" + 0.006*"soul" + 0.006*"wicked" + 0.005*"words" + 0.005*"sword" + 0.005*"midst" + 0.005*"hosts" + 0.004*"iniquity" + 0.004*"righteous" + 0.004*"holy"'),
 (2,
  '0.024*"david" + 0.015*"saul" + 0.010*"philistines" + 0.008*"joshua" + 0.007*"servants" + 0.007*"servant" + 0.007*"cities" + 0.006*"priests" + 0.006*"samuel" + 0.006*"kings"'),
 (3,
  '0.013*"jerusalem" + 0.012*"kings" + 0.011*"david" + 0.010*"fathers" + 0.008*"father" + 0.008*"solomon" + 0.006*"years" + 0.006*"cities" + 0.006*"priests" + 0.006*"servants"')]

In [91]:
# Let's try 5 topics
ldana = models.LdaModel(corpus=corpusna, num_topics=5, id2word=id2wordna, passes=10)
ldana.print_topics()

[(0,
  '0.008*"soul" + 0.007*"way" + 0.007*"wicked" + 0.006*"righteous" + 0.005*"midst" + 0.005*"words" + 0.004*"iniquity" + 0.004*"sword" + 0.004*"holy" + 0.004*"righteousness"'),
 (1,
  '0.025*"moses" + 0.008*"aaron" + 0.008*"egypt" + 0.007*"tent" + 0.007*"fathers" + 0.007*"cities" + 0.006*"joshua" + 0.006*"tribe" + 0.006*"border" + 0.006*"levites"'),
 (2,
  '0.019*"david" + 0.009*"kings" + 0.008*"fathers" + 0.008*"saul" + 0.008*"father" + 0.007*"priest" + 0.007*"jerusalem" + 0.006*"servants" + 0.006*"philistines" + 0.006*"servant"'),
 (3,
  '0.013*"hosts" + 0.011*"jerusalem" + 0.008*"babylon" + 0.006*"egypt" + 0.006*"words" + 0.006*"sword" + 0.005*"jeremiah" + 0.005*"cities" + 0.004*"zion" + 0.004*"way"'),
 (4,
  '0.017*"father" + 0.015*"jacob" + 0.013*"joseph" + 0.012*"years" + 0.011*"wife" + 0.009*"abraham" + 0.008*"brother" + 0.008*"brethren" + 0.008*"egypt" + 0.007*"pharaoh"')]

## Identify Topics in Each Document

Out of the 9 topic models we looked at, the nouns and adjectives, 4 topic one made the most sense. So let's pull that down here and run it through some more iterations to get more fine-tuned topics.

In [93]:
# Our final LDA model (for now)
ldana = models.LdaModel(corpus=corpusna, num_topics=4, id2word=id2wordna, passes=80)
ldana.print_topics()

[(0,
  '0.026*"david" + 0.013*"saul" + 0.009*"kings" + 0.008*"philistines" + 0.007*"cities" + 0.007*"father" + 0.007*"fathers" + 0.007*"servants" + 0.006*"jerusalem" + 0.006*"joshua"'),
 (1,
  '0.012*"jerusalem" + 0.009*"kings" + 0.008*"fathers" + 0.007*"babylon" + 0.006*"solomon" + 0.006*"father" + 0.006*"year" + 0.006*"priests" + 0.005*"servants" + 0.005*"years"'),
 (2,
  '0.007*"soul" + 0.007*"way" + 0.006*"words" + 0.006*"wicked" + 0.005*"midst" + 0.005*"hosts" + 0.005*"sword" + 0.005*"iniquity" + 0.004*"righteous" + 0.004*"holy"'),
 (3,
  '0.020*"moses" + 0.009*"egypt" + 0.008*"priest" + 0.007*"aaron" + 0.007*"father" + 0.007*"years" + 0.007*"tent" + 0.007*"fathers" + 0.007*"altar" + 0.006*"holy"')]

These four topics look pretty decent. Let's settle on these for now.
* Topic 0: Monarchy
* Topic 1: Politics
* Topic 2: Morality
* Topic 3: Avodah

In [164]:
topic_title = {0.0:'Monarchy',1.0:'Politics',2.0:'Morality',3.0:'Avodah'}
# Let's take a look at which topics each transcript contains
corpus_transformed = ldana[corpusna]
# type(corpus_transformed)
sent_topics_df = pd.DataFrame()

# Get main topic in each document
for i, row in enumerate(corpus_transformed):
    row = sorted(row, key=lambda x: (x[1]), reverse=True)
    # Get the Dominant topic, Perc Contribution and Keywords for each document
    for j, (topic_num, prop_topic) in enumerate(row):
        if j == 0:  # => dominant topic
            wp = ldana.show_topic(topic_num)
            topic_keywords = ", ".join([word for word, prop in wp])
            sent_topics_df = sent_topics_df.append(pd.Series([topic_title[int(topic_num)], round(prop_topic,4), topic_keywords]), ignore_index=True)
        else:
            break
sent_topics_df.columns = ['Dominant_Topic', 'Perc_Contribution', 'Topic_Keywords']
sent_topics_df.index = data_clean.index
sent_topics_df = sent_topics_df.sort_values(by=['Perc_Contribution'],ascending=False)
sent_topics_df

,Dominant_Topic,Perc_Contribution,Topic_Keywords
Exodus,Avodah,0.9999,"moses, egypt, priest, aaron, father, years, te..."
Psalms,Morality,0.9999,"soul, way, words, wicked, midst, hosts, sword,..."
Kings,Politics,0.9999,"jerusalem, kings, fathers, babylon, solomon, f..."
Isaiah,Morality,0.9999,"soul, way, words, wicked, midst, hosts, sword,..."
Numbers,Avodah,0.9999,"moses, egypt, priest, aaron, father, years, te..."
Proverbs,Morality,0.9998,"soul, way, words, wicked, midst, hosts, sword,..."
Job,Morality,0.9998,"soul, way, words, wicked, midst, hosts, sword,..."
Leviticus,Avodah,0.9998,"moses, egypt, priest, aaron, father, years, te..."
EzraNehemiah,Politics,0.9998,"jerusalem, kings, fathers, babylon, solomon, f..."
Genesis,Avodah,0.9998,"moses, egypt, priest, aaron, father, years, te..."
Esther,Monarchy,0.9993,"david, saul, kings, philistines, cities, fathe..."
Ecclesiastes,Morality,0.9992,"soul, way, words, wicked, midst, hosts, sword,..."
SongofSongs,Morality,0.9988,"soul, way, words, wicked, midst, hosts, sword,..."
Lamentations,Morality,0.9988,"soul, way, words, wicked, midst, hosts, sword,..."
Habakkuk,Morality,0.9974,"soul, way, words, wicked, midst, hosts, sword,..."
Nahum,Morality,0.9971,"soul, way, words, wicked, midst, hosts, sword,..."
Jonah,Morality,0.9958,"soul, way, words, wicked, midst, hosts, sword,..."
Daniel,Morality,0.9893,"soul, way, words, wicked, midst, hosts, sword,..."
Micah,Morality,0.9854,"soul, way, words, wicked, midst, hosts, sword,..."
Joel,Morality,0.9790,"soul, way, words, wicked, midst, hosts, sword,..."
Samuel,Monarchy,0.9673,"david, saul, kings, philistines, cities, fathe..."
Judges,Politics,0.9645,"jerusalem, kings, fathers, babylon, solomon, f..."
Chronicles,Monarchy,0.9257,"david, saul, kings, philistines, cities, fathe..."
Joshua,Monarchy,0.9166,"david, saul, kings, philistines, cities, fathe..."
Zephaniah,Morality,0.8882,"soul, way, words, wicked, midst, hosts, sword,..."
Hosea,Morality,0.8792,"soul, way, words, wicked, midst, hosts, sword,..."
Ezekiel,Morality,0.8511,"soul, way, words, wicked, midst, hosts, sword,..."
Malachi,Morality,0.7908,"soul, way, words, wicked, midst, hosts, sword,..."
Obadiah,Morality,0.7489,"soul, way, words, wicked, midst, hosts, sword,..."
Ruth,Morality,0.6741,"soul, way, words, wicked, midst, hosts, sword,..."
Amos,Morality,0.6641,"soul, way, words, wicked, midst, hosts, sword,..."
Deuteronomy,Avodah,0.6615,"moses, egypt, priest, aaron, father, years, te..."
Haggai,Politics,0.6372,"jerusalem, kings, fathers, babylon, solomon, f..."
Zechariah,Morality,0.5328,"soul, way, words, wicked, midst, hosts, sword,..."
Jeremiah,Politics,0.5054,"jerusalem, kings, fathers, babylon, solomon, f..."

For a first pass of LDA, these kind of make sense to me, so we'll call it a day for now.
* Topic 0: mom, parents [Anthony, Hasan, Louis, Ricky]
* Topic 1: husband, wife [Ali, John, Mike]
* Topic 2: guns [Bill, Bo, Jim]
* Topic 3: profanity [Dave, Joe]

## Additional Exercises

1. Try further modifying the parameters of the topic models above and see if you can get better topics.
2. Create a new topic model that includes terms from a different [part of speech](https://www.ling.upenn.edu/courses/Fall_2003/ling001/penn_treebank_pos.html) and see if you can get better topics.